// SVIR: Semantic Video Intermediate Representation, schema v0.1.
//
// Rules (frozen at the end of Phase 1; see docs/svir-schema-v0.1.md):
//   * Changes after the freeze are ADDITIVE only: new fields, new messages, new enum values.
//   * Never renumber, retype or reuse a field number. Removed fields go in `reserved`.
//   * All times are int64 ticks of the container header's `timescale`, so semantic
//     times line up exactly with pixel timestamps.
//   * Every block carries `layer` (field 14) and `pixel_ref` (field 15). Block-specific
//     fields use numbers 1..13.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: svir.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Layer says which part of the semantic stream a block belongs to. Numbers 1..4 match
// the layer ids in the .virex section table. UNSPECIFIED means "use the default for
// this block type" (see schema.DefaultLayer).
type Layer int32

const (
	Layer_LAYER_UNSPECIFIED Layer = 0
	Layer_L0_ENTITY         Layer = 1 // entities and objects
	Layer_L1_EVENT          Layer = 2 // events, actions, relations, scenes, temporal blocks
	Layer_L2_TEXT           Layer = 3 // text (OCR)
	Layer_L3_EMBEDDING      Layer = 4 // embeddings and captions
)

// Enum value maps for Layer.
var (
	Layer_name = map[int32]string{
		0: "LAYER_UNSPECIFIED",
		1: "L0_ENTITY",
		2: "L1_EVENT",
		3: "L2_TEXT",
		4: "L3_EMBEDDING",
	}
	Layer_value = map[string]int32{
		"LAYER_UNSPECIFIED": 0,
		"L0_ENTITY":         1,
		"L1_EVENT":          2,
		"L2_TEXT":           3,
		"L3_EMBEDDING":      4,
	}
)

func (x Layer) Enum() *Layer {
	p := new(Layer)
	*p = x
	return p
}

func (x Layer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layer) Descriptor() protoreflect.EnumDescriptor {
	return file_svir_proto_enumTypes[0].Descriptor()
}

func (Layer) Type() protoreflect.EnumType {
	return &file_svir_proto_enumTypes[0]
}

func (x Layer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layer.Descriptor instead.
func (Layer) EnumDescriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{0}
}

type TemporalKind int32

const (
	TemporalKind_TEMPORAL_KIND_UNSPECIFIED TemporalKind = 0
	TemporalKind_TEMPORAL_KEY              TemporalKind = 1 // full state at this time (like a key frame)
	TemporalKind_TEMPORAL_DELTA            TemporalKind = 2 // only what changed since base_t (like a delta frame)
)

// Enum value maps for TemporalKind.
var (
	TemporalKind_name = map[int32]string{
		0: "TEMPORAL_KIND_UNSPECIFIED",
		1: "TEMPORAL_KEY",
		2: "TEMPORAL_DELTA",
	}
	TemporalKind_value = map[string]int32{
		"TEMPORAL_KIND_UNSPECIFIED": 0,
		"TEMPORAL_KEY":              1,
		"TEMPORAL_DELTA":            2,
	}
)

func (x TemporalKind) Enum() *TemporalKind {
	p := new(TemporalKind)
	*p = x
	return p
}

func (x TemporalKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemporalKind) Descriptor() protoreflect.EnumDescriptor {
	return file_svir_proto_enumTypes[1].Descriptor()
}

func (TemporalKind) Type() protoreflect.EnumType {
	return &file_svir_proto_enumTypes[1]
}

func (x TemporalKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemporalKind.Descriptor instead.
func (TemporalKind) EnumDescriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{1}
}

// BBox is a rectangle in normalised coordinates: 0..1, origin top-left,
// x/y = top-left corner, w/h = size. Resolution independent.
type BBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	W             float32                `protobuf:"fixed32,3,opt,name=w,proto3" json:"w,omitempty"`
	H             float32                `protobuf:"fixed32,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BBox) Reset() {
	*x = BBox{}
	mi := &file_svir_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BBox) ProtoMessage() {}

func (x *BBox) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BBox.ProtoReflect.Descriptor instead.
func (*BBox) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{0}
}

func (x *BBox) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BBox) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BBox) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *BBox) GetH() float32 {
	if x != nil {
		return x.H
	}
	return 0
}

// PixelRef points back to the pixels a fact was derived from (paper contribution C4).
type PixelRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TStart        int64                  `protobuf:"varint,1,opt,name=t_start,json=tStart,proto3" json:"t_start,omitempty"`          // ticks
	TEnd          int64                  `protobuf:"varint,2,opt,name=t_end,json=tEnd,proto3" json:"t_end,omitempty"`                // ticks; equal to t_start for a single frame
	FrameId       *int64                 `protobuf:"varint,3,opt,name=frame_id,json=frameId,proto3,oneof" json:"frame_id,omitempty"` // 0-based display-order frame index; absent if not frame-specific
	Bbox          *BBox                  `protobuf:"bytes,4,opt,name=bbox,proto3" json:"bbox,omitempty"`                             // region inside the frame, if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PixelRef) Reset() {
	*x = PixelRef{}
	mi := &file_svir_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PixelRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixelRef) ProtoMessage() {}

func (x *PixelRef) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixelRef.ProtoReflect.Descriptor instead.
func (*PixelRef) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{1}
}

func (x *PixelRef) GetTStart() int64 {
	if x != nil {
		return x.TStart
	}
	return 0
}

func (x *PixelRef) GetTEnd() int64 {
	if x != nil {
		return x.TEnd
	}
	return 0
}

func (x *PixelRef) GetFrameId() int64 {
	if x != nil && x.FrameId != nil {
		return *x.FrameId
	}
	return 0
}

func (x *PixelRef) GetBbox() *BBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

// Entity: something that exists over a span of time and can be referred to by id.
type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                             // e.g. "person", "slide", "car"
	FirstSeen     int64                  `protobuf:"varint,3,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"` // ticks
	LastSeen      int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`    // ticks
	Layer         Layer                  `protobuf:"varint,14,opt,name=layer,proto3,enum=virex.svir.Layer" json:"layer,omitempty"`
	PixelRef      *PixelRef              `protobuf:"bytes,15,opt,name=pixel_ref,json=pixelRef,proto3" json:"pixel_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_svir_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{2}
}

func (x *Entity) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetFirstSeen() int64 {
	if x != nil {
		return x.FirstSeen
	}
	return 0
}

func (x *Entity) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *Entity) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *Entity) GetPixelRef() *PixelRef {
	if x != nil {
		return x.PixelRef
	}
	return nil
}

// ObjectBlock: one detection of an entity at one time.
type ObjectBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Class         string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"` // detector class name
	Bbox          *BBox                  `protobuf:"bytes,3,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Confidence    *float32               `protobuf:"fixed32,4,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"` // 0..1, absent if unknown
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`          // ticks
	Layer         Layer                  `protobuf:"varint,14,opt,name=layer,proto3,enum=virex.svir.Layer" json:"layer,omitempty"`
	PixelRef      *PixelRef              `protobuf:"bytes,15,opt,name=pixel_ref,json=pixelRef,proto3" json:"pixel_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectBlock) Reset() {
	*x = ObjectBlock{}
	mi := &file_svir_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectBlock) ProtoMessage() {}

func (x *ObjectBlock) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectBlock.ProtoReflect.Descriptor instead.
func (*ObjectBlock) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectBlock) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *ObjectBlock) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ObjectBlock) GetBbox() *BBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *ObjectBlock) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *ObjectBlock) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ObjectBlock) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *ObjectBlock) GetPixelRef() *PixelRef {
	if x != nil {
		return x.PixelRef
	}
	return nil
}

// TextBlock: text read from the picture (OCR).
type TextBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Bbox          *BBox                  `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Confidence    *float32               `protobuf:"fixed32,3,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ticks
	Layer         Layer                  `protobuf:"varint,14,opt,name=layer,proto3,enum=virex.svir.Layer" json:"layer,omitempty"`
	PixelRef      *PixelRef              `protobuf:"bytes,15,opt,name=pixel_ref,json=pixelRef,proto3" json:"pixel_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextBlock) Reset() {
	*x = TextBlock{}
	mi := &file_svir_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextBlock) ProtoMessage() {}

func (x *TextBlock) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextBlock.ProtoReflect.Descriptor instead.
func (*TextBlock) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{4}
}

func (x *TextBlock) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextBlock) GetBbox() *BBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *TextBlock) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *TextBlock) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TextBlock) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *TextBlock) GetPixelRef() *PixelRef {
	if x != nil {
		return x.PixelRef
	}
	return nil
}

// ActionBlock: an entity doing something over an interval.
type ActionBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     uint64                 `protobuf:"varint,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // e.g. "writing", "walking"
	Start         int64                  `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`  // ticks
	End           int64                  `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`      // ticks
	Confidence    *float32               `protobuf:"fixed32,5,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Layer         Layer                  `protobuf:"varint,14,opt,name=layer,proto3,enum=virex.svir.Layer" json:"layer,omitempty"`
	PixelRef      *PixelRef              `protobuf:"bytes,15,opt,name=pixel_ref,json=pixelRef,proto3" json:"pixel_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionBlock) Reset() {
	*x = ActionBlock{}
	mi := &file_svir_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionBlock) ProtoMessage() {}

func (x *ActionBlock) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionBlock.ProtoReflect.Descriptor instead.
func (*ActionBlock) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{5}
}

func (x *ActionBlock) GetSubjectId() uint64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *ActionBlock) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionBlock) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ActionBlock) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *ActionBlock) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *ActionBlock) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *ActionBlock) GetPixelRef() *PixelRef {
	if x != nil {
		return x.PixelRef
	}
	return nil
}

// EventBlock: something that happened, possibly involving several entities.
type EventBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`    // e.g. "slide_change", "person_enters"
	Start         int64                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"` // ticks
	End           int64                  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`     // ticks
	EntityIds     []uint64               `protobuf:"varint,4,rep,packed,name=entity_ids,json=entityIds,proto3" json:"entity_ids,omitempty"`
	Region        *BBox                  `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Confidence    *float32               `protobuf:"fixed32,6,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Layer         Layer                  `protobuf:"varint,14,opt,name=layer,proto3,enum=virex.svir.Layer" json:"layer,omitempty"`
	PixelRef      *PixelRef              `protobuf:"bytes,15,opt,name=pixel_ref,json=pixelRef,proto3" json:"pixel_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBlock) Reset() {
	*x = EventBlock{}
	mi := &file_svir_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBlock) ProtoMessage() {}

func (x *EventBlock) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBlock.ProtoReflect.Descriptor instead.
func (*EventBlock) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{6}
}

func (x *EventBlock) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventBlock) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *EventBlock) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *EventBlock) GetEntityIds() []uint64 {
	if x != nil {
		return x.EntityIds
	}
	return nil
}

func (x *EventBlock) GetRegion() *BBox {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *EventBlock) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *EventBlock) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *EventBlock) GetPixelRef() *PixelRef {
	if x != nil {
		return x.PixelRef
	}
	return nil
}

// RelationBlock: subject --relation--> object over an interval.
type RelationBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     uint64                 `protobuf:"varint,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"` // e.g. "holding", "left_of"
	ObjectId      uint64                 `protobuf:"varint,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Start         int64                  `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"` // ticks
	End           int64                  `protobuf:"varint,5,opt,name=end,proto3" json:"end,omitempty"`     // ticks
	Confidence    *float32               `protobuf:"fixed32,6,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Id            uint64                 `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"` // 0 = not given; TemporalBlock refers to relations by id
	Layer         Layer                  `protobuf:"varint,14,opt,name=layer,proto3,enum=virex.svir.Layer" json:"layer,omitempty"`
	PixelRef      *PixelRef              `protobuf:"bytes,15,opt,name=pixel_ref,json=pixelRef,proto3" json:"pixel_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationBlock) Reset() {
	*x = RelationBlock{}
	mi := &file_svir_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationBlock) ProtoMessage() {}

func (x *RelationBlock) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationBlock.ProtoReflect.Descriptor instead.
func (*RelationBlock) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{7}
}

func (x *RelationBlock) GetSubjectId() uint64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *RelationBlock) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *RelationBlock) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *RelationBlock) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *RelationBlock) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *RelationBlock) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *RelationBlock) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RelationBlock) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *RelationBlock) GetPixelRef() *PixelRef {
	if x != nil {
		return x.PixelRef
	}
	return nil
}

// AttributeBlock: a property of an entity over an interval, like Visual Genome's
// "horse is brown": key = "color", value = "brown".
type AttributeBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`      // e.g. "color", "state"
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`  // e.g. "brown", "open"
	Start         int64                  `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"` // ticks
	End           int64                  `protobuf:"varint,5,opt,name=end,proto3" json:"end,omitempty"`     // ticks
	Confidence    *float32               `protobuf:"fixed32,6,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Layer         Layer                  `protobuf:"varint,14,opt,name=layer,proto3,enum=virex.svir.Layer" json:"layer,omitempty"`
	PixelRef      *PixelRef              `protobuf:"bytes,15,opt,name=pixel_ref,json=pixelRef,proto3" json:"pixel_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeBlock) Reset() {
	*x = AttributeBlock{}
	mi := &file_svir_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeBlock) ProtoMessage() {}

func (x *AttributeBlock) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeBlock.ProtoReflect.Descriptor instead.
func (*AttributeBlock) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{8}
}

func (x *AttributeBlock) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *AttributeBlock) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AttributeBlock) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AttributeBlock) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *AttributeBlock) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *AttributeBlock) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *AttributeBlock) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *AttributeBlock) GetPixelRef() *PixelRef {
	if x != nil {
		return x.PixelRef
	}
	return nil
}

// SceneBlock: a labelled stretch of video.
type SceneBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`     // short label, e.g. "lecture hall"
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"` // longer description
	Start         int64                  `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`    // ticks
	End           int64                  `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`        // ticks
	Layer         Layer                  `protobuf:"varint,14,opt,name=layer,proto3,enum=virex.svir.Layer" json:"layer,omitempty"`
	PixelRef      *PixelRef              `protobuf:"bytes,15,opt,name=pixel_ref,json=pixelRef,proto3" json:"pixel_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneBlock) Reset() {
	*x = SceneBlock{}
	mi := &file_svir_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneBlock) ProtoMessage() {}

func (x *SceneBlock) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneBlock.ProtoReflect.Descriptor instead.
func (*SceneBlock) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{9}
}

func (x *SceneBlock) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SceneBlock) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *SceneBlock) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SceneBlock) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *SceneBlock) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *SceneBlock) GetPixelRef() *PixelRef {
	if x != nil {
		return x.PixelRef
	}
	return nil
}

// TemporalBlock: scene-graph state over time, for temporal compression in later phases.
// A KEY block is a full snapshot; a DELTA block lists only what changed since the KEY
// block at base_t (the Key-SG / Delta-SG idea from CSGCoT).
type TemporalBlock struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Kind               TemporalKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=virex.svir.TemporalKind" json:"kind,omitempty"`
	TStart             int64                  `protobuf:"varint,2,opt,name=t_start,json=tStart,proto3" json:"t_start,omitempty"`                                               // ticks
	TEnd               int64                  `protobuf:"varint,3,opt,name=t_end,json=tEnd,proto3" json:"t_end,omitempty"`                                                     // ticks
	BaseT              int64                  `protobuf:"varint,4,opt,name=base_t,json=baseT,proto3" json:"base_t,omitempty"`                                                  // DELTA only: t_start of the KEY block this builds on
	ActiveEntityIds    []uint64               `protobuf:"varint,5,rep,packed,name=active_entity_ids,json=activeEntityIds,proto3" json:"active_entity_ids,omitempty"`           // KEY: all active entities
	AddedEntityIds     []uint64               `protobuf:"varint,6,rep,packed,name=added_entity_ids,json=addedEntityIds,proto3" json:"added_entity_ids,omitempty"`              // DELTA: entities that appeared
	RemovedEntityIds   []uint64               `protobuf:"varint,7,rep,packed,name=removed_entity_ids,json=removedEntityIds,proto3" json:"removed_entity_ids,omitempty"`        // DELTA: entities that disappeared
	ActiveRelationIds  []uint64               `protobuf:"varint,8,rep,packed,name=active_relation_ids,json=activeRelationIds,proto3" json:"active_relation_ids,omitempty"`     // KEY: all active relations (RelationBlock.id)
	AddedRelationIds   []uint64               `protobuf:"varint,9,rep,packed,name=added_relation_ids,json=addedRelationIds,proto3" json:"added_relation_ids,omitempty"`        // DELTA: relations that appeared
	RemovedRelationIds []uint64               `protobuf:"varint,10,rep,packed,name=removed_relation_ids,json=removedRelationIds,proto3" json:"removed_relation_ids,omitempty"` // DELTA: relations that ended
	Layer              Layer                  `protobuf:"varint,14,opt,name=layer,proto3,enum=virex.svir.Layer" json:"layer,omitempty"`
	PixelRef           *PixelRef              `protobuf:"bytes,15,opt,name=pixel_ref,json=pixelRef,proto3" json:"pixel_ref,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TemporalBlock) Reset() {
	*x = TemporalBlock{}
	mi := &file_svir_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalBlock) ProtoMessage() {}

func (x *TemporalBlock) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalBlock.ProtoReflect.Descriptor instead.
func (*TemporalBlock) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{10}
}

func (x *TemporalBlock) GetKind() TemporalKind {
	if x != nil {
		return x.Kind
	}
	return TemporalKind_TEMPORAL_KIND_UNSPECIFIED
}

func (x *TemporalBlock) GetTStart() int64 {
	if x != nil {
		return x.TStart
	}
	return 0
}

func (x *TemporalBlock) GetTEnd() int64 {
	if x != nil {
		return x.TEnd
	}
	return 0
}

func (x *TemporalBlock) GetBaseT() int64 {
	if x != nil {
		return x.BaseT
	}
	return 0
}

func (x *TemporalBlock) GetActiveEntityIds() []uint64 {
	if x != nil {
		return x.ActiveEntityIds
	}
	return nil
}

func (x *TemporalBlock) GetAddedEntityIds() []uint64 {
	if x != nil {
		return x.AddedEntityIds
	}
	return nil
}

func (x *TemporalBlock) GetRemovedEntityIds() []uint64 {
	if x != nil {
		return x.RemovedEntityIds
	}
	return nil
}

func (x *TemporalBlock) GetActiveRelationIds() []uint64 {
	if x != nil {
		return x.ActiveRelationIds
	}
	return nil
}

func (x *TemporalBlock) GetAddedRelationIds() []uint64 {
	if x != nil {
		return x.AddedRelationIds
	}
	return nil
}

func (x *TemporalBlock) GetRemovedRelationIds() []uint64 {
	if x != nil {
		return x.RemovedRelationIds
	}
	return nil
}

func (x *TemporalBlock) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *TemporalBlock) GetPixelRef() *PixelRef {
	if x != nil {
		return x.PixelRef
	}
	return nil
}

// EmbeddingBlock: a vector and/or caption for a frame or region (layer L3).
type EmbeddingBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"` // model that produced the vector
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Caption       string                 `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ticks
	Layer         Layer                  `protobuf:"varint,14,opt,name=layer,proto3,enum=virex.svir.Layer" json:"layer,omitempty"`
	PixelRef      *PixelRef              `protobuf:"bytes,15,opt,name=pixel_ref,json=pixelRef,proto3" json:"pixel_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingBlock) Reset() {
	*x = EmbeddingBlock{}
	mi := &file_svir_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingBlock) ProtoMessage() {}

func (x *EmbeddingBlock) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingBlock.ProtoReflect.Descriptor instead.
func (*EmbeddingBlock) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{11}
}

func (x *EmbeddingBlock) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbeddingBlock) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *EmbeddingBlock) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *EmbeddingBlock) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EmbeddingBlock) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *EmbeddingBlock) GetPixelRef() *PixelRef {
	if x != nil {
		return x.PixelRef
	}
	return nil
}

// SVIRDocument is the content of a SEMANTIC section (or one time segment / one layer
// of it). An empty document is valid: it is what Phase 1 writes.
type SVIRDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaMajor   uint32                 `protobuf:"varint,1,opt,name=schema_major,json=schemaMajor,proto3" json:"schema_major,omitempty"`
	SchemaMinor   uint32                 `protobuf:"varint,2,opt,name=schema_minor,json=schemaMinor,proto3" json:"schema_minor,omitempty"`
	Layer         Layer                  `protobuf:"varint,3,opt,name=layer,proto3,enum=virex.svir.Layer" json:"layer,omitempty"` // which layer this document holds; UNSPECIFIED = mixed / all
	TStart        int64                  `protobuf:"varint,4,opt,name=t_start,json=tStart,proto3" json:"t_start,omitempty"`       // ticks; both 0 = whole stream
	TEnd          int64                  `protobuf:"varint,5,opt,name=t_end,json=tEnd,proto3" json:"t_end,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,10,rep,name=entities,proto3" json:"entities,omitempty"`
	Objects       []*ObjectBlock         `protobuf:"bytes,11,rep,name=objects,proto3" json:"objects,omitempty"`
	Texts         []*TextBlock           `protobuf:"bytes,12,rep,name=texts,proto3" json:"texts,omitempty"`
	Actions       []*ActionBlock         `protobuf:"bytes,13,rep,name=actions,proto3" json:"actions,omitempty"`
	Events        []*EventBlock          `protobuf:"bytes,14,rep,name=events,proto3" json:"events,omitempty"`
	Relations     []*RelationBlock       `protobuf:"bytes,15,rep,name=relations,proto3" json:"relations,omitempty"`
	Scenes        []*SceneBlock          `protobuf:"bytes,16,rep,name=scenes,proto3" json:"scenes,omitempty"`
	Temporals     []*TemporalBlock       `protobuf:"bytes,17,rep,name=temporals,proto3" json:"temporals,omitempty"`
	Embeddings    []*EmbeddingBlock      `protobuf:"bytes,18,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	Attributes    []*AttributeBlock      `protobuf:"bytes,19,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SVIRDocument) Reset() {
	*x = SVIRDocument{}
	mi := &file_svir_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SVIRDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SVIRDocument) ProtoMessage() {}

func (x *SVIRDocument) ProtoReflect() protoreflect.Message {
	mi := &file_svir_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SVIRDocument.ProtoReflect.Descriptor instead.
func (*SVIRDocument) Descriptor() ([]byte, []int) {
	return file_svir_proto_rawDescGZIP(), []int{12}
}

func (x *SVIRDocument) GetSchemaMajor() uint32 {
	if x != nil {
		return x.SchemaMajor
	}
	return 0
}

func (x *SVIRDocument) GetSchemaMinor() uint32 {
	if x != nil {
		return x.SchemaMinor
	}
	return 0
}

func (x *SVIRDocument) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *SVIRDocument) GetTStart() int64 {
	if x != nil {
		return x.TStart
	}
	return 0
}

func (x *SVIRDocument) GetTEnd() int64 {
	if x != nil {
		return x.TEnd
	}
	return 0
}

func (x *SVIRDocument) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SVIRDocument) GetObjects() []*ObjectBlock {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *SVIRDocument) GetTexts() []*TextBlock {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *SVIRDocument) GetActions() []*ActionBlock {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *SVIRDocument) GetEvents() []*EventBlock {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SVIRDocument) GetRelations() []*RelationBlock {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *SVIRDocument) GetScenes() []*SceneBlock {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *SVIRDocument) GetTemporals() []*TemporalBlock {
	if x != nil {
		return x.Temporals
	}
	return nil
}

func (x *SVIRDocument) GetEmbeddings() []*EmbeddingBlock {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *SVIRDocument) GetAttributes() []*AttributeBlock {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_svir_proto protoreflect.FileDescriptor

const file_svir_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"svir.proto\x12\n" +
	"virex.svir\">\n" +
	"\x04BBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x02R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x02R\x01h\"\x8b\x01\n" +
	"\bPixelRef\x12\x17\n" +
	"\at_start\x18\x01 \x01(\x03R\x06tStart\x12\x13\n" +
	"\x05t_end\x18\x02 \x01(\x03R\x04tEnd\x12\x1e\n" +
	"\bframe_id\x18\x03 \x01(\x03H\x00R\aframeId\x88\x01\x01\x12$\n" +
	"\x04bbox\x18\x04 \x01(\v2\x10.virex.svir.BBoxR\x04bboxB\v\n" +
	"\t_frame_id\"\xc4\x01\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"first_seen\x18\x03 \x01(\x03R\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\x12'\n" +
	"\x05layer\x18\x0e \x01(\x0e2\x11.virex.svir.LayerR\x05layer\x121\n" +
	"\tpixel_ref\x18\x0f \x01(\v2\x14.virex.svir.PixelRefR\bpixelRef\"\x94\x02\n" +
	"\vObjectBlock\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12$\n" +
	"\x04bbox\x18\x03 \x01(\v2\x10.virex.svir.BBoxR\x04bbox\x12#\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02H\x00R\n" +
	"confidence\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12'\n" +
	"\x05layer\x18\x0e \x01(\x0e2\x11.virex.svir.LayerR\x05layer\x121\n" +
	"\tpixel_ref\x18\x0f \x01(\v2\x14.virex.svir.PixelRefR\bpixelRefB\r\n" +
	"\v_confidence\"\xf9\x01\n" +
	"\tTextBlock\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12$\n" +
	"\x04bbox\x18\x02 \x01(\v2\x10.virex.svir.BBoxR\x04bbox\x12#\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02H\x00R\n" +
	"confidence\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12'\n" +
	"\x05layer\x18\x0e \x01(\x0e2\x11.virex.svir.LayerR\x05layer\x121\n" +
	"\tpixel_ref\x18\x0f \x01(\v2\x14.virex.svir.PixelRefR\bpixelRefB\r\n" +
	"\v_confidence\"\xfc\x01\n" +
	"\vActionBlock\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\x04R\tsubjectId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x03R\x03end\x12#\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02H\x00R\n" +
	"confidence\x88\x01\x01\x12'\n" +
	"\x05layer\x18\x0e \x01(\x0e2\x11.virex.svir.LayerR\x05layer\x121\n" +
	"\tpixel_ref\x18\x0f \x01(\v2\x14.virex.svir.PixelRefR\bpixelRefB\r\n" +
	"\v_confidence\"\xa1\x02\n" +
	"\n" +
	"EventBlock\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x03R\x03end\x12\x1d\n" +
	"\n" +
	"entity_ids\x18\x04 \x03(\x04R\tentityIds\x12(\n" +
	"\x06region\x18\x05 \x01(\v2\x10.virex.svir.BBoxR\x06region\x12#\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02H\x00R\n" +
	"confidence\x88\x01\x01\x12'\n" +
	"\x05layer\x18\x0e \x01(\x0e2\x11.virex.svir.LayerR\x05layer\x121\n" +
	"\tpixel_ref\x18\x0f \x01(\v2\x14.virex.svir.PixelRefR\bpixelRefB\r\n" +
	"\v_confidence\"\xaf\x02\n" +
	"\rRelationBlock\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\x04R\tsubjectId\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\x04R\bobjectId\x12\x14\n" +
	"\x05start\x18\x04 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x05 \x01(\x03R\x03end\x12#\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02H\x00R\n" +
	"confidence\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\a \x01(\x04R\x02id\x12'\n" +
	"\x05layer\x18\x0e \x01(\x0e2\x11.virex.svir.LayerR\x05layer\x121\n" +
	"\tpixel_ref\x18\x0f \x01(\v2\x14.virex.svir.PixelRefR\bpixelRefB\r\n" +
	"\v_confidence\"\x8d\x02\n" +
	"\x0eAttributeBlock\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x14\n" +
	"\x05start\x18\x04 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x05 \x01(\x03R\x03end\x12#\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02H\x00R\n" +
	"confidence\x88\x01\x01\x12'\n" +
	"\x05layer\x18\x0e \x01(\x0e2\x11.virex.svir.LayerR\x05layer\x121\n" +
	"\tpixel_ref\x18\x0f \x01(\v2\x14.virex.svir.PixelRefR\bpixelRefB\r\n" +
	"\v_confidence\"\xc0\x01\n" +
	"\n" +
	"SceneBlock\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x03R\x03end\x12'\n" +
	"\x05layer\x18\x0e \x01(\x0e2\x11.virex.svir.LayerR\x05layer\x121\n" +
	"\tpixel_ref\x18\x0f \x01(\v2\x14.virex.svir.PixelRefR\bpixelRef\"\xf2\x03\n" +
	"\rTemporalBlock\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.virex.svir.TemporalKindR\x04kind\x12\x17\n" +
	"\at_start\x18\x02 \x01(\x03R\x06tStart\x12\x13\n" +
	"\x05t_end\x18\x03 \x01(\x03R\x04tEnd\x12\x15\n" +
	"\x06base_t\x18\x04 \x01(\x03R\x05baseT\x12*\n" +
	"\x11active_entity_ids\x18\x05 \x03(\x04R\x0factiveEntityIds\x12(\n" +
	"\x10added_entity_ids\x18\x06 \x03(\x04R\x0eaddedEntityIds\x12,\n" +
	"\x12removed_entity_ids\x18\a \x03(\x04R\x10removedEntityIds\x12.\n" +
	"\x13active_relation_ids\x18\b \x03(\x04R\x11activeRelationIds\x12,\n" +
	"\x12added_relation_ids\x18\t \x03(\x04R\x10addedRelationIds\x120\n" +
	"\x14removed_relation_ids\x18\n" +
	" \x03(\x04R\x12removedRelationIds\x12'\n" +
	"\x05layer\x18\x0e \x01(\x0e2\x11.virex.svir.LayerR\x05layer\x121\n" +
	"\tpixel_ref\x18\x0f \x01(\v2\x14.virex.svir.PixelRefR\bpixelRef\"\xd6\x01\n" +
	"\x0eEmbeddingBlock\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1a\n" +
	"\x06vector\x18\x02 \x03(\x02B\x02\x10\x01R\x06vector\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12'\n" +
	"\x05layer\x18\x0e \x01(\x0e2\x11.virex.svir.LayerR\x05layer\x121\n" +
	"\tpixel_ref\x18\x0f \x01(\v2\x14.virex.svir.PixelRefR\bpixelRef\"\xb8\x05\n" +
	"\fSVIRDocument\x12!\n" +
	"\fschema_major\x18\x01 \x01(\rR\vschemaMajor\x12!\n" +
	"\fschema_minor\x18\x02 \x01(\rR\vschemaMinor\x12'\n" +
	"\x05layer\x18\x03 \x01(\x0e2\x11.virex.svir.LayerR\x05layer\x12\x17\n" +
	"\at_start\x18\x04 \x01(\x03R\x06tStart\x12\x13\n" +
	"\x05t_end\x18\x05 \x01(\x03R\x04tEnd\x12.\n" +
	"\bentities\x18\n" +
	" \x03(\v2\x12.virex.svir.EntityR\bentities\x121\n" +
	"\aobjects\x18\v \x03(\v2\x17.virex.svir.ObjectBlockR\aobjects\x12+\n" +
	"\x05texts\x18\f \x03(\v2\x15.virex.svir.TextBlockR\x05texts\x121\n" +
	"\aactions\x18\r \x03(\v2\x17.virex.svir.ActionBlockR\aactions\x12.\n" +
	"\x06events\x18\x0e \x03(\v2\x16.virex.svir.EventBlockR\x06events\x127\n" +
	"\trelations\x18\x0f \x03(\v2\x19.virex.svir.RelationBlockR\trelations\x12.\n" +
	"\x06scenes\x18\x10 \x03(\v2\x16.virex.svir.SceneBlockR\x06scenes\x127\n" +
	"\ttemporals\x18\x11 \x03(\v2\x19.virex.svir.TemporalBlockR\ttemporals\x12:\n" +
	"\n" +
	"embeddings\x18\x12 \x03(\v2\x1a.virex.svir.EmbeddingBlockR\n" +
	"embeddings\x12:\n" +
	"\n" +
	"attributes\x18\x13 \x03(\v2\x1a.virex.svir.AttributeBlockR\n" +
	"attributes*Z\n" +
	"\x05Layer\x12\x15\n" +
	"\x11LAYER_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tL0_ENTITY\x10\x01\x12\f\n" +
	"\bL1_EVENT\x10\x02\x12\v\n" +
	"\aL2_TEXT\x10\x03\x12\x10\n" +
	"\fL3_EMBEDDING\x10\x04*S\n" +
	"\fTemporalKind\x12\x1d\n" +
	"\x19TEMPORAL_KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTEMPORAL_KEY\x10\x01\x12\x12\n" +
	"\x0eTEMPORAL_DELTA\x10\x02B\x1aZ\x18virex/svir/schema;schemab\x06proto3"

var (
	file_svir_proto_rawDescOnce sync.Once
	file_svir_proto_rawDescData []byte
)

func file_svir_proto_rawDescGZIP() []byte {
	file_svir_proto_rawDescOnce.Do(func() {
		file_svir_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svir_proto_rawDesc), len(file_svir_proto_rawDesc)))
	})
	return file_svir_proto_rawDescData
}

var file_svir_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_svir_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_svir_proto_goTypes = []any{
	(Layer)(0),             // 0: virex.svir.Layer
	(TemporalKind)(0),      // 1: virex.svir.TemporalKind
	(*BBox)(nil),           // 2: virex.svir.BBox
	(*PixelRef)(nil),       // 3: virex.svir.PixelRef
	(*Entity)(nil),         // 4: virex.svir.Entity
	(*ObjectBlock)(nil),    // 5: virex.svir.ObjectBlock
	(*TextBlock)(nil),      // 6: virex.svir.TextBlock
	(*ActionBlock)(nil),    // 7: virex.svir.ActionBlock
	(*EventBlock)(nil),     // 8: virex.svir.EventBlock
	(*RelationBlock)(nil),  // 9: virex.svir.RelationBlock
	(*AttributeBlock)(nil), // 10: virex.svir.AttributeBlock
	(*SceneBlock)(nil),     // 11: virex.svir.SceneBlock
	(*TemporalBlock)(nil),  // 12: virex.svir.TemporalBlock
	(*EmbeddingBlock)(nil), // 13: virex.svir.EmbeddingBlock
	(*SVIRDocument)(nil),   // 14: virex.svir.SVIRDocument
}
var file_svir_proto_depIdxs = []int32{
	2,  // 0: virex.svir.PixelRef.bbox:type_name -> virex.svir.BBox
	0,  // 1: virex.svir.Entity.layer:type_name -> virex.svir.Layer
	3,  // 2: virex.svir.Entity.pixel_ref:type_name -> virex.svir.PixelRef
	2,  // 3: virex.svir.ObjectBlock.bbox:type_name -> virex.svir.BBox
	0,  // 4: virex.svir.ObjectBlock.layer:type_name -> virex.svir.Layer
	3,  // 5: virex.svir.ObjectBlock.pixel_ref:type_name -> virex.svir.PixelRef
	2,  // 6: virex.svir.TextBlock.bbox:type_name -> virex.svir.BBox
	0,  // 7: virex.svir.TextBlock.layer:type_name -> virex.svir.Layer
	3,  // 8: virex.svir.TextBlock.pixel_ref:type_name -> virex.svir.PixelRef
	0,  // 9: virex.svir.ActionBlock.layer:type_name -> virex.svir.Layer
	3,  // 10: virex.svir.ActionBlock.pixel_ref:type_name -> virex.svir.PixelRef
	2,  // 11: virex.svir.EventBlock.region:type_name -> virex.svir.BBox
	0,  // 12: virex.svir.EventBlock.layer:type_name -> virex.svir.Layer
	3,  // 13: virex.svir.EventBlock.pixel_ref:type_name -> virex.svir.PixelRef
	0,  // 14: virex.svir.RelationBlock.layer:type_name -> virex.svir.Layer
	3,  // 15: virex.svir.RelationBlock.pixel_ref:type_name -> virex.svir.PixelRef
	0,  // 16: virex.svir.AttributeBlock.layer:type_name -> virex.svir.Layer
	3,  // 17: virex.svir.AttributeBlock.pixel_ref:type_name -> virex.svir.PixelRef
	0,  // 18: virex.svir.SceneBlock.layer:type_name -> virex.svir.Layer
	3,  // 19: virex.svir.SceneBlock.pixel_ref:type_name -> virex.svir.PixelRef
	1,  // 20: virex.svir.TemporalBlock.kind:type_name -> virex.svir.TemporalKind
	0,  // 21: virex.svir.TemporalBlock.layer:type_name -> virex.svir.Layer
	3,  // 22: virex.svir.TemporalBlock.pixel_ref:type_name -> virex.svir.PixelRef
	0,  // 23: virex.svir.EmbeddingBlock.layer:type_name -> virex.svir.Layer
	3,  // 24: virex.svir.EmbeddingBlock.pixel_ref:type_name -> virex.svir.PixelRef
	0,  // 25: virex.svir.SVIRDocument.layer:type_name -> virex.svir.Layer
	4,  // 26: virex.svir.SVIRDocument.entities:type_name -> virex.svir.Entity
	5,  // 27: virex.svir.SVIRDocument.objects:type_name -> virex.svir.ObjectBlock
	6,  // 28: virex.svir.SVIRDocument.texts:type_name -> virex.svir.TextBlock
	7,  // 29: virex.svir.SVIRDocument.actions:type_name -> virex.svir.ActionBlock
	8,  // 30: virex.svir.SVIRDocument.events:type_name -> virex.svir.EventBlock
	9,  // 31: virex.svir.SVIRDocument.relations:type_name -> virex.svir.RelationBlock
	11, // 32: virex.svir.SVIRDocument.scenes:type_name -> virex.svir.SceneBlock
	12, // 33: virex.svir.SVIRDocument.temporals:type_name -> virex.svir.TemporalBlock
	13, // 34: virex.svir.SVIRDocument.embeddings:type_name -> virex.svir.EmbeddingBlock
	10, // 35: virex.svir.SVIRDocument.attributes:type_name -> virex.svir.AttributeBlock
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_svir_proto_init() }
func file_svir_proto_init() {
	if File_svir_proto != nil {
		return
	}
	file_svir_proto_msgTypes[1].OneofWrappers = []any{}
	file_svir_proto_msgTypes[3].OneofWrappers = []any{}
	file_svir_proto_msgTypes[4].OneofWrappers = []any{}
	file_svir_proto_msgTypes[5].OneofWrappers = []any{}
	file_svir_proto_msgTypes[6].OneofWrappers = []any{}
	file_svir_proto_msgTypes[7].OneofWrappers = []any{}
	file_svir_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svir_proto_rawDesc), len(file_svir_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svir_proto_goTypes,
		DependencyIndexes: file_svir_proto_depIdxs,
		EnumInfos:         file_svir_proto_enumTypes,
		MessageInfos:      file_svir_proto_msgTypes,
	}.Build()
	File_svir_proto = out.File
	file_svir_proto_goTypes = nil
	file_svir_proto_depIdxs = nil
}
